development:
  adapter: postgresql
  encoding: utf8
  database: google_app_development
  host: localhost
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: utf8
  database: google_app_test
  host: localhost
  pool: 5
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: utf8
  database: google_app_development
  host: localhost
  pool: 5
  username: postgres
  password: 123
